### ISSUE TITLE
tautology: missing metadata.yml file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/coq#7]
We need a metadata.yml file in order to be able to display the exercise on the site and construct the README.

Usually it's provided by the common pool of problem definitions in https://github.com/exercism/x-common, but for track-specific exercises it needs to have it here. 
See https://github.com/exercism/xrust/blob/master/exercises/luhn-from/metadata.yml for an example.

@IanWhitney have you had a chance to write up some notes about track-specific exercises?

@Insti, @IanWhitney we should probably [open a discussion](https://github.com/exercism/discussions/issues) about putting these files in `.meta` instead of in the root exercise directory.

**Comment by Insti** [comment]
We should probably add something to configlet to check for this too.

**Comment by vzaliva** [comment]
We just have not gotten around creatingYML file for the exercise.

**Comment by kytrinyx** [comment]
@vzaliva Please keep all incomplete exercises in branches. As soon as they land in master they get included in on the site, and when metadata is missing I get a breaking build. I can work around it manually, but it makes it harder to deploy.

**Comment by proger** [comment]
@kytrinyx is it enough to keep them out of config.json? (i don't oppose to branches but just wondering — as I was wiring them in there)

**Comment by kytrinyx** [comment]
@proger if you keep them out of the config.json the build will fail because it detects the presence of exercises that are not configured.

Branches really are the way to go in this case—sorry!

(In the meanwhile, if you'd touch a `metadata.yml` file so that I can deploy without workarounds, I'd appreciate it!

**Comment by Insti** [comment]
@kytrinyx could you please review https://github.com/exercism/trackler/pull/46 concerning  the metadata.yml location.

**Comment by proger** [comment]
Added!

**Comment by kytrinyx** [comment]
Thank you @proger.

@Insti just a heads up: I won't be able to review this (or anything really) until next week.

**Comment by Insti** [comment]
@kytrinyx OK, thanks for letting me know.
