### ISSUE TITLE
Code rendering failure

### ISSUE THREAD

**Issue by Insti** [exercism/coq#9]
A solution submitted containing the line:

```coq
Definition hello:string := "Hello, World!".
```
(This *is* valid Coq right?)

Will not display due to an error.
This is due to a bug the gem Exercism uses for code rendering: Rouge.

Example: http://exercism.io/exercises/28bf6ba542204e3ab252de710158920a (this will fail until the problem is fixed.)

**Comment by Insti** [comment]
What probably needs to happen.
- [x] submit a bug to the rouge project https://github.com/jneen/rouge
- [x] wait for it to be fixed
- [x] update the version of Rouge exercism.io uses to the fixed version

**Comment by kytrinyx** [comment]
If you can narrow this down to the smallest possible failing case, then I'd be happy to submit the bug with a failing test to rouge.

**Comment by NobbZ** [comment]
The linked code is mine, but is this really related to Rogue not beeing able to highlight it? My Idris submissions are all fine and aren't supported by Rogue as well...

**Comment by petertseng** [comment]
hi there, any possibility that https://github.com/jneen/rouge/commit/1cab83aea79285f0bcc27977adcca799e776df5c#diff-94a0f7acd72b147ecb8c7b7c8bbc0504 fixes it

sorry to intrude

**Comment by NobbZ** [comment]
Oh. @petertseng just mentioned in the gitter, that Rogue claims to support coq, there's a lexer:

https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/coq.rb

**Comment by Insti** [comment]
> hi there, any possibility that jneen/rouge@1cab83a#diff-94a0f7acd72b147ecb8c7b7c8bbc0504 fixes it

Yes, it does. Updating rouge fixes the problem.

**Comment by Insti** [comment]
Thanks @kytrinyx :heart:
